### ISSUE TITLE
Task not always taken by a consumer

### ISSUE THREAD

**Issue by djannot** [adjust/rmq#16]
I have a consumer function called Consume:

```
type TaskConsumer struct {
}

func (consumer *TaskConsumer) Consume(delivery rmq.Delivery) {
```

And I have several instances of my applications running.
On each instance, I add a consumer and start consuming tasks:

```
taskQueue := rmqConnection.OpenQueue("scheduleTasks")
taskQueue.StartConsuming(10, time.Second)
taskConsumer := &TaskConsumer{}
taskQueue.AddConsumer(uuid.NewV4().String(), taskConsumer)
```

And only one instance is publishing tasks:
```
taskQueue.Publish(UserId)
```

Am I doing something wrong ?

**Comment by wellle** [comment]
So what exactly is the problem here? You have a single producer and a bunch of consumers. How do you know that a task is not taken? In what cases does that happen?

Are you sure the consumers are still running when you publish the delivery? Where you call `AddConsumer` you need to make sure the program doesn't just finish. You might want do drop a `select{}` there or something similar.

**Comment by djannot** [comment]
@wellle I was using a `select{}` to make sure the program was not exiting, but when I was registering several new tasks at the same time, only one was consumed by a worker.
I'm now using another library.
Thanks for your help.
