### ISSUE TITLE
Prefetch limit & poll duration

### ISSUE THREAD

**Issue by codepushr** [adjust/rmq#22]
Hi, I want to use this library for push notifications so they don't vanish from memory once the service crashes. Do you think this is a sensible use-case (also considering production use)?

When setting up a small example project I figured that the prefetch limit and poll duration somehow don't align. Setting a limit of 2 and a timeout of 10 seconds still sucks up random chunks of 7-10 deliveries at once, depending how fast I add items to the queue.

```go
func main() {
	// Setup redis and notification queue
	redis := rmq.OpenConnection("my service", "tcp", "localhost:6379", 1)
	queue := redis.OpenQueue("notifications")

	c := Consumer{}

	// Start consuming
	queue.StartConsuming(2, time.Second*10)
	queue.AddConsumer("consumer", &c)

	e := echo.New()
	e.Run(standard.New(":" + port))
}

func (c *Consumer) Consume(delivery rmq.Delivery) {
	log.Println(delivery.Payload())
	delivery.Ack()
}
```

You can see that they got all the same second in the timestamp:

```
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
2016/10/22 00:07:01 bla
```

**Comment by codepushr** [comment]
It seems I just misunderstood how these parameters work :)

**Comment by wellle** [comment]
@codepushr: Well if it would work the way you seem to expect, then you would basically limit your throughput to 2 deliveries every 10 seconds. I don't see why you would want that and that's not supported.

So basically as long as there are deliveries in the queue, rmq takes up to `prefetchLimit` deliveries and send them over to the consumer. Once they are consumed, and as long as there are more deliveries in the queue, it gets the next batch and so on. So the `prefetchLimit` controls how big those batches are that we get before calling `Consume` on them.

Now, if we find the queue to be empty at some point, because we drained them while nothing new was produced, we need to decide what to do now. We don't want to busy wait on it, because an empty queue should not take a lot of resources. So we should wait a bit and then check again if new deliveries have been produced in the meantime. And that's what the `pollDuration` is for.

So in your example a full queue would be drained in batches of 2. And since your consumer is fast, it manages to consume all batches in the same second. Go try and see if your consumer takes longer (while waiting for a push notification for example).

Once the queue is empty it will sleep 10 seconds and check again, sleep 10 seconds and check again, and so on.

If you're okay with having notifications delayed by up to 10 seconds, that would be ok. If you want smaller delays, you might reduce the poll duration to 1s or 100ms.

I hope that clears that up. And yes I think this sounds like a good use case for rmq.
