### ISSUE TITLE
Can we have persistence and durability of the message queue to be used as logging?

### ISSUE THREAD

**Issue by streetlist** [adjust/rmq#37]
Can we have persistence and durability of the message queue to be used as logging?

**Comment by wellle** [comment]
@streetlist: Thanks for your interest! Since rmq just builds on top of Redis, I think your best option is to just set up Redis to be persistent and durable, see https://redis.io/topics/persistence

Alternatively you could use a non durable Redis and have rmq consumers which just move all your logging deliveries to any other persistent storage. But at that point I'm not sure if you even need rmq then.

Since durability/persistence happens at the Redis level, I would say this topic is generally not going to be a goal for rmq itself.

**Comment by wellle** [comment]
Closing as there's nothing to be done here.
