### ISSUE TITLE
ReturnAllUnacked

### ISSUE THREAD

**Issue by iomatters** [adjust/rmq#42]
Hi,

Why wouldn't you expose ReturnAllUnacked via Queue ? Just thinking of how do I handle a consumer's death, there is alway an option of the unpacked elements to be left which means data loss.

Thanks.

**Comment by wellle** [comment]
Hi, it's important that it's impossible to remove unacked deliveries on a queue which is currently being consumed (otherwise you'd end up with double delivery). So exposing that function would be dangerous.

That's why we have the `rmq.Cleaner` struct instead. See [example/cleaner/cleaner.go](https://github.com/adjust/rmq/blob/master/example/cleaner/cleaner.go) for an example on how to use it. It's best to deploy that as a separate service which just periodically checks for dead connections (missing heartbeat) and then returns all unacked deliveries in all queues which had been open by dead connections. (We use it with `time.Tick(time.Minute)`)

**Comment by geekio** [comment]
Hi,

Hi,
Getting back to the exposed Connection interface, it's missing Close() func in my case. Clean() does not work out due to the "active" (unclosed) connections. When it comes to consuming, I can't use rmq.OpenConnection and close it within a func anyway as a batch is being processed in the callback func Consume().

One more thing, take a look at the code from redis_wrapper.go:
func checkErr(err error) (ok bool) {
        switch err {
        case nil:
                return true
        case redis.Nil:
                return false
        default:
                log.Panicf("rmq redis error is not nil %s", err)
                return false
        }
Is there any specific reasoning behind the panic? Why just not return false? I am still struggling with the case when Redis can go offline and my rmq based app must handle the situation, proceeding with producing/consuming/cleaning when Redis is up.

Thanks.

**Comment by geekio** [comment]
Yes, already got it, it waits for the "heartbeat" key to be expired. Thx.

**Comment by thebiggestlebowski** [comment]
Is it a problem to have multiple concurrent cleaner processes?

**Comment by thebiggestlebowski** [comment]
And by the way, thank you for this library ;)

**Comment by wellle** [comment]
> Is it a problem to have multiple concurrent cleaner processes?

Yes, I would NOT recommend running multiple cleaners at the same time. They might interfere with each other when trying to clean up the same queue at the same time.

**Comment by wellle** [comment]
Closing, nothing to be done here.
