### ISSUE TITLE
Could you expose the queue.RemoveConsumer function through the Queue interface?

### ISSUE THREAD

**Issue by ympons** [adjust/rmq#5]
Hi,
Thanks a lot for this package. Could you expose the queue.RemoveConsumer function through the Queue interface?

Thanks!

**Comment by wellle** [comment]
@ympons: Thanks for your interest!

I'm not sure that function is doing what you think it does. Could you give me a bit more context about your use case? Why and when do you want to remove a consumer from a queue, and what exactly do you expect to happen? Once we're on the same page we can see if `RemoveConsumer` fits the bill or what we want to do instead.

**Comment by ympons** [comment]
@wellle : Thanks for taking the time to respond. 

We're using the rmq package as the core of one of our microservices. This microservice is responsible for creating the queues given the name and registering the consumers to specific queues. We have default/predefined queues and consumers into the microservices and the rmq package fits well this context.
The other context is that we expose some HTTP endpoints for specific apps responsible for sending and receiving messages from the microservice. When an app needs to receive/process specific messages, it sends an HTTP request to the microservice and this one creates or reuses the necessary consumers to approach this task.

We would like to have access to the RemoveConsumer function to remove those consumers that are not being used or won't be used anymore once we send back the messages to apps clients.

Thanks!

**Comment by wellle** [comment]
Ok, so it would be used like this:

- open queue `q1`
- start consuming on `q1`
- add consumers `c1`, `c2`, `c3` to consume on `q1`
- all three consumers receive deliveries
- remove consumer `c2` from consuming on `q1`
- consumers `c1` and `c3` should still continue to consume from `q1`
- consumer `c2` should not receive any deliveries anymore

Can you confirm this is what you need? Because `RemoveConsumer` currently does not actually stop consuming, it just removes the consumer from some bookkeeping data structure. This would need to be properly implemented before exposing it.

**Comment by ympons** [comment]
@wellle : yep exactly what I need.

**Comment by ympons** [comment]
Hi @wellle, we implemented this feature through a ClosableConsumer interface, so the consumer provides a `closer channel` that we use it to stop the goroutine. You can check the implementation in [our fork](https://github.com/adjust/rmq/compare/master...Spatially:master)

Here's an example of our consumer:
```go
type Consumer struct {
        ....
	closer chan bool
}

func (c *Consumer) Close() error {
	c.closer <- true
	return nil
}

func (c *Consumer) Closer() chan bool {
	return c.closer
}

func (c *Consumer) ConsumeOneTime() bool {
	return true // true: if you want to consume only one delivery
}
```

**Comment by wellle** [comment]
Interesting! Thanks for your work, some quick comments:

Why do you use a type switch in `consumerClosableConsume` instead of passing a `ClosableConsumer` into `AddClosableConsumer`? Why would one ever want to call that function on a normal `Consumer`? 

You would need to include `Consumer` in `ClosableConsumer` to make this work (or add `Consume` to `ClosableConsumer`).

Also you might want to switch the case statements to allow closing the channel even if the `deliveryChan` never gets empty. I believe currently it only closes if no delivery can be consumed.

Why is `Close` part of the interface, it's not used there.

**Comment by ympons** [comment]
Thanks for checking!

> Why do you use a type switch in consumerClosableConsume instead of passing a ClosableConsumer into AddClosableConsumer? Why would one ever want to call that function on a normal Consumer?

Our intention is to move the implementation to the `queue.consumerConsume` function and use `AddConsumer` instead of `AddClosableConsumer`. In this way the lib can keep the same api.
What do you think about it?

> Also you might want to switch the case statements to allow closing the channel even if the deliveryChan never gets empty. I believe currently it only closes if no delivery can be consumed. Why is Close part of the interface, it's not used there.

I'm not sure if I understand this part. It closes when you call `consumer.Close()`.

**Comment by ympons** [comment]
I like the idea of implementing this feature in a separated method instead of moving it to `queue.consumerConsume`.

> Why is Close part of the interface, it's not used there.

It's just a little restriction by the fact that we're operating over Closable consumer. I believe it provides a proper place to introduce any logic related with closing the consumer.

**Comment by wellle** [comment]
Lets continue in #7.

**Comment by wellle** [comment]
I believe this is no longer needed since #33.
