### ISSUE TITLE
Publish() returns a boolean instead of an int

### ISSUE THREAD

**Issue by Xeoncross** [adjust/rmq#50]
The official Redis command states the response is an [int of the list length](https://redis.io/commands/lpush).

The `RedisClient` interface here [returns a bool instead](https://github.com/adjust/rmq/blob/master/redis_client.go#L12)

https://github.com/adjust/rmq/blob/master/redis_wrapper.go#L37

**Comment by wellle** [comment]
Yep, that's true. Is that a problem? How?

**Comment by Xeoncross** [comment]
I was going to use that information to pass back to another system about the state of the queue. I was assuming the redis client worked the same. The work-around is just to make another request that `LLEN` for the same information.

**Comment by wellle** [comment]
For stats you can use `CollectStats()`, it's mentioned in the readme here: https://github.com/adjust/rmq#statistics

See also `/example/handler/main.go` on how to create a stats handler. Instead of calling `GetHtml` you can also just JSON marshal such an `rmq.Stats` instance if you prefer using JSON.

**Comment by wellle** [comment]
Nothing to be done here.
