### ISSUE TITLE
how to modify the delivery use your api?

### ISSUE THREAD

**Issue by MagicSong** [adjust/rmq#52]
i have a task queue storing tasks, but the task may fail sometimes, i want to modify some fields before using delivery.Reject().For example incr the field `retry`,and when `retry` greater than some number, we will give up the task. Is there possible to use your api to do that?

**Comment by wellle** [comment]
@MagicSong: Yes. One thing you can always do is just publish it again as a new task. So in case you want to put it back into the same queue after modifying it, just modify, publish to the queue and ack the original delivery you're currently consuming.

For retries specifically there's another way we are using as well, which is using push queues. Lets say you have a queue named `abc` and want to retry up to five times. We'll use five push queues called `abc-p1` to `abc-p5`. Now when you open queue `abc`, set its push queue to be `abc-p1` (via `SetPushQueue()`). For `abc-p1` the push queue shall be `abc-p2` etc. For `abc-p5` we don't set up a push queue. Now you could run the same consumer on each of those six queues. Or they could be slightly different, for example you might want to wait a bit before retrying, so you could have the consumers wait for certain ages of the deliveries.

In any case, whenever you find yourself in the situation where you'd want to retry a delivery, just call `delivery.Push()` instead of acking or rejecting it. That way it gets moved over to the proper push queue. If push is called from a queue without push queue (like `abc-p5` in our example), then it behaves as if `Reject()` was called, it goes into `failed`.

But push queues are pretty much just a convenience for this sort of use case. (where we encode the information about the retry count not into the delivery, but in the queue it's currently in)

If you need more flexibility you can always just publish a new delivery into any queue and ack the current one.

**Comment by MagicSong** [comment]
@wellle Very thanks for your kind reply. i think `push queues` is more graceful than republish because i don't need to pass the `queue` to `consumer` or notify other who has ability to publish(in my app, only producer can publish). I will try to use `push queue`. Thanks again!
