### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by ghostsquad** [adjust/rmq#58]
Any plans on exposing queue metrics via Prometheus endpoint? If not, I'd like to contribute.

**Comment by wellle** [comment]
@ghostsquad: We don't have any plans to add prometheus metrics, so feel free to add some 👍

**Comment by ghostsquad** [comment]
Will do!

**Comment by pffreitas** [comment]
I've done this on https://github.com/pffreitas/rmqprom

It's based on my personal needs, so any help on how to best design it would be much appreciated. 

Also, I've done it on a separated repo as I understand there's no reason to add prometheus dependencies on RMQ, but happy to hear otherwise opinions.

**Comment by wellle** [comment]
@pffreitas: Thank you, that's awesome! Would you want to open a PR here to add a link to your repo from our README?

**Comment by pffreitas** [comment]
@wellle: Awesome! Just put a PR up for that (#83). Thanks!

**Comment by wellle** [comment]
Thanks again!
