### ISSUE TITLE
Tons of connections being opened, cleaner is no help :(

### ISSUE THREAD

**Issue by rectof** [adjust/rmq#89]
I've been using rmq for a little under a week now, and unfortunately, I've started to run into some issues.

![image](https://user-images.githubusercontent.com/20710643/82768488-5d8c8b80-9dfd-11ea-96d1-992aa5f3e220.png)

I'm currently sharing one connection across 4-5 queues, in the past, I've had little to no issues doing this, but as shown by the screenshot above, the single connection seems to spawning a lot more than expected, over time the connections build and cause redis to timeout. Below is a snippet of how I'm opening and sharing the connection, alongside how the cleaner is running, if you have any suggestions on how to improve this or what may cause the mass amount of clients please let me know, thanks!

```go
var connection rmq.Connection

func OpenConnection(url string) {
	opt, _ := redis.ParseURL(url)
	opt.MaxRetries = 5
	redisConn := rmq.OpenConnectionWithRedisClient("heartbeat", redis.NewClient(opt))
	connection = redisConn
	go func() {
		cleaner := rmq.NewCleaner(redisConn)
		for range time.Tick(time.Second) {
			err := cleaner.Clean()
			if err != nil {
				sentry.CaptureException(err)
			}
		}
	}()
}

**Comment by nehaboob** [comment]
Hi @rectof  I have recently started using rmq as well and I am doing a couple of things. 

1. Share redis client between connections rather than getting new client for each connection to the queue. This should reduce number of connected clients to redis.
```
var connection rmq.Connection
opt, _ := redis.ParseURL(url)
opt.MaxRetries = 5
redis_client = redis.NewClient(opt)

func OpenConnection(url string) {
	redisConn := rmq.OpenConnectionWithRedisClient("heartbeat", redis_client)
	connection = redisConn
	go func() {
		cleaner := rmq.NewCleaner(redisConn)
		for range time.Tick(time.Second) {
			err := cleaner.Clean()
			if err != nil {
				sentry.CaptureException(err)
			}
		}
	}()
```
}
2. Stop the connection heartbeat once done with the work so that cleaner can clean the connection. 
In my case I stop the heartbeat of the connection which are using just once for publishing to the queue. 
`connection.StopHeartbeat()
`
Hope this helps. Please share if you come across more ideas.
