### ISSUE TITLE
How to use rmq with multiple consumers?

### ISSUE THREAD

**Issue by DoubleDi** [adjust/rmq#91]
About a year ago i couldn't get the queue working for multiple consumers. 
On scheduling multiple tasks to rmq at one point of my application i couldn't get them on my consumers part after application restarted as `OpenConnectionWithRedisClient` always generates a unique queue name `name := fmt.Sprintf("%s-%s", tag, uniuri.NewLen(6))`.

So i forked and removed the this. And also added `ReturnAllUnacked()` method so when the consumer restarts it can start processing them again. Something like this: https://github.com/DoubleDi/rmq/commits?author=DoubleDi

But i am interested - am i doing something wrong? Or what are the intentions of making the name unique?

**Comment by wellle** [comment]
Yes, you need to run a cleaner regularly.

When you have a consumer it fetches unacked deliveries from Redis. When the consumer dies or gets killed, those unacked deliveries remain unacked. The cleaner will see that the consumer is dead and return the unacked deliveries to the ready list. From there a new consumer can fetch them again.

I improved the documentation about that in the currently open PR, you can look at it here: https://github.com/adjust/rmq/tree/8-dont-panic#cleaner

And you shouldn't remove the random part. That's quite important so that multiple connections can manage their separate list of unacked deliveries and don't interfere with each other.

**Comment by DoubleDi** [comment]
Thanks for the advice!
When is the don't panic branch going live?

**Comment by wellle** [comment]
As mentioned in the PR, we are currently testing it internally before we merge the PR. But feel free to already use it from that branch 👍
